using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using MLib3.MVVM.Navigation.Generator;
using Xunit;

namespace MLib3.MVVM.Navigation.SourceGenerated.Tests;

public class NavigationSourceGeneratorTests
{
    private const string ExampleVMClassText = @"
using MLib3.MVVM;

namespace TestNamespace;

public class ExampleVM : ViewModel
{
    
}

public class Example2VM : ViewModel
{
    
}
";

    private const string ExpectedGeneratedClassText = @"// <auto-generated/>
using FluentResults;

namespace MLib3.MVVM.Navigation; 

public static class NavigatorExtensions
{
    // ExampleVM
    public static Result<TestNamespace.ExampleVM> GotoExample(this INavigator navigator) => navigator.Goto<TestNamespace.ExampleVM>();
    public static Result<TestNamespace.ExampleVM> PushExample(this INavigator navigator) => navigator.Push<TestNamespace.ExampleVM>();
    public static Result<TestNamespace.ExampleVM> SlideExample(this INavigator navigator) => navigator.Slide<TestNamespace.ExampleVM>();

    // Example2VM
    public static Result<TestNamespace.Example2VM> GotoExample2(this INavigator navigator) => navigator.Goto<TestNamespace.Example2VM>();
    public static Result<TestNamespace.Example2VM> PushExample2(this INavigator navigator) => navigator.Push<TestNamespace.Example2VM>();
    public static Result<TestNamespace.Example2VM> SlideExample2(this INavigator navigator) => navigator.Slide<TestNamespace.Example2VM>();
}
";

    [Fact]
    public void GenerateReportMethod()
    {
        // Create an instance of the source generator.
        var generator = new NavigationSourceGenerator();

        // Source generators should be tested using 'GeneratorDriver'.
        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(nameof(NavigationSourceGenerator),
            new[] { CSharpSyntaxTree.ParseText(ExampleVMClassText) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(MLib3.MVVM.ViewModel).Assembly.Location),
            });

        // Run generators and retrieve all results.
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        // All generated files can be found in 'RunResults.GeneratedTrees'.
        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("NavigatorExtensions.g.cs"));

        // Complex generators should be tested using text comparison.
        Assert.Equal(ExpectedGeneratedClassText, generatedFileSyntax.GetText().ToString(),
            ignoreLineEndingDifferences: true);
    }
}