<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Title>MLib3.MVVM.Navigation</Title>
        <Authors>Andreas Naumann</Authors>
        <Description>A library for view model based navigation in WPF applicaitons</Description>
        <Copyright>2026 @ Andreas Naumann</Copyright>
        <PackageIcon>icon.png</PackageIcon>
        <PackageProjectUrl>https://github.com/mrmorrandir/MLib3</PackageProjectUrl>
        <RepositoryUrl>https://github.com/mrmorrandir/MLib3</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>2.4.0</Version>
        <PackageTags>MVVM;Navigation;ViewModels</PackageTags>
        <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\..\assets\icon.png">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
        <Link>icon.png</Link>
      </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MLib3.MVVM.Navigation\MLib3.MVVM.Navigation.csproj" />
        <ProjectReference Include="..\MLib3.MVVM.Navigation.Generator\MLib3.MVVM.Navigation.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
