using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MLib3.MVVM.Navigation.Generator;

/// <summary>
/// A sample source generator that creates a custom report based on class properties. The target class should be annotated with the 'Generators.ReportAttribute' attribute.
/// When using the source code as a baseline, an incremental source generator is preferable because it reduces the performance overhead.
/// </summary>
[Generator]
public class NavigationSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var viewModelProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => IsPotentialViewModelBaseImplementor(s),
                (ctx, _) => GetViewModelBaseImplementors(ctx))
            .Where(t => t != null)
            .Collect();
        
        context.RegisterSourceOutput(viewModelProvider, (spc, source) => 
            GeneratePartialNavigator(spc, source.Where(t => t != null).Select(t => (ViewModelBaseType)t!).ToImmutableArray()));
    }
    
    private bool IsPotentialViewModelBaseImplementor(SyntaxNode syntaxNode)
    {
        if (syntaxNode is not ClassDeclarationSyntax classDeclaration)
            return false;

        // Check if the class name ends with VM
        if (!classDeclaration.Identifier.Text.EndsWith("VM"))
            return false;

        // Check if class derives from ViewModelBase
        if (classDeclaration.BaseList is null)
            return false;

        return true;
    }

    private static ViewModelBaseType? GetViewModelBaseImplementors(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (classSymbol == null)
            return null;

        if (!classSymbol.Name.EndsWith("VM"))
            return null;

        var implementsViewModelBase = false;
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.ToDisplayString() == "MLib3.MVVM.ViewModel" || 
                baseType.ToDisplayString() == "MLib3.MVVM.ViewModelValidator" ||
                baseType.ToDisplayString() == "MLib3.MVVM.ValidatableViewModel")
            {
                implementsViewModelBase = true;
                break;
            }

            baseType = baseType.BaseType;
        }

        if (!implementsViewModelBase) return null;

        // Get the Namespace of the class
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        // Get the Name of the class
        var className = classSymbol.Name;

        return new ViewModelBaseType(namespaceName, className);
    }

  
    private void GeneratePartialNavigator(SourceProductionContext context, ImmutableArray<ViewModelBaseType> viewModelBaseTypes)
    {
        var navigationMethods = new StringBuilder();

        foreach (var viewModelBaseType in viewModelBaseTypes)
        {
            var viewModelName = viewModelBaseType.Name;
            var viewModelNameTrimmed = viewModelName.Trim().Replace("VM", "");
            var viewModelNamespace = viewModelBaseType.Namespace;
            
            navigationMethods.AppendLine($"    // {viewModelName}");
            navigationMethods.AppendLine($"    public static Result<{viewModelNamespace}.{viewModelName}> Goto{viewModelNameTrimmed}(this INavigator navigator) => navigator.Goto<{viewModelNamespace}.{viewModelName}>();");
            navigationMethods.AppendLine($"    public static Result<{viewModelNamespace}.{viewModelName}> Push{viewModelNameTrimmed}(this INavigator navigator) => navigator.Push<{viewModelNamespace}.{viewModelName}>();");
            navigationMethods.AppendLine($"    public static Result<{viewModelNamespace}.{viewModelName}> Slide{viewModelNameTrimmed}(this INavigator navigator) => navigator.Slide<{viewModelNamespace}.{viewModelName}>();");
            navigationMethods.AppendLine();
        }

        var source = $@"// <auto-generated/>
using FluentResults;

namespace MLib3.MVVM.Navigation; 

public static class NavigatorExtensions
{{
{navigationMethods.ToString().TrimEnd()}
}}
";

        context.AddSource("NavigatorExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}