<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.0.0</Version>
        <Title>MLib3.AspNetCore.Application</Title>
        <Description>A library providing helpfull classes for AspNetCore APIs and their BusinessLogic (CleanArchitecture).</Description>
        <PackageProjectUrl>https://github.com/mrmorrandir/MLib3</PackageProjectUrl>
        <PackageIcon>icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/mrmorrandir/MLib3</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>AspNetCore;Architecture;CQRS;CleanArchitecture;FluentResults</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\MLib3.AspNetCore.Application.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentResults" Version="4.0.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\assets\icon.png">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
            <Link>icon.png</Link>
        </None>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
