<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <IsPackable>true</IsPackable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentResults" Version="4.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
